sudo: false
language: node_js

node_js:
- '10'
- '12'

# keep the npm cache around to speed up installs
cache:
  yarn: true
  directories:
  - node_modules

install:
- yarn install --frozen-lockfile --audit --non-interactive

script:
- yarn run coverage
